// Generated by tools.sdkgen; DO NOT EDIT.
#nullable enable

namespace Headroom.GeneratedPilot;

public sealed class Client : IDisposable
{
    private readonly Transport transport;
    public Client(string baseUrl = "http://localhost:8787", ClientOptions? options = null) =>
        transport = new Transport(baseUrl, options ?? ClientOptions.Default);

    public async Task<RetrieveResponse> RetrieveAsync(RetrieveRequest body, CancellationToken cancellationToken = default)
    {
        var path = "/v1/retrieve";
        return await transport.SendAsync<RetrieveRequest, RetrieveResponse>(HttpMethod.Post, path, body, true, cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetrieveResponse> RetrieveGetAsync(string hash_key, CancellationToken cancellationToken = default)
    {
        var path = "/v1/retrieve/{hash_key}";
        path = path.Replace("{hash_key}", Transport.PathSegment(hash_key), StringComparison.Ordinal);
        return await transport.SendAsync<object, RetrieveResponse>(HttpMethod.Get, path, null, false, cancellationToken).ConfigureAwait(false);
    }

    public void Dispose() => transport.Dispose();
}
