// Generated by tools.sdkgen; DO NOT EDIT.
import { Transport, pathSegment } from "./runtime.js";
import type { RequestOptions, TransportOptions } from "./runtime.js";
import { schemas } from "./schemas.js";
import type { RetrievalError, RetrieveRequest, RetrieveResponse } from "./models.js";

export class Client {
  private readonly transport: Transport;
  constructor(baseUrl = "http://localhost:8787", options: TransportOptions = {}) {
    this.transport = new Transport(baseUrl, options);
  }
  async retrieve(body: RetrieveRequest, options: RequestOptions = {}): Promise<RetrieveResponse> {
    let path = "/v1/retrieve";
    return this.transport.request<RetrieveResponse>("POST", path, body, "RetrieveRequest", "RetrieveResponse", schemas, options);
  }
  async retrieveGet(hashKey: string, options: RequestOptions = {}): Promise<RetrieveResponse> {
    let path = "/v1/retrieve/{hash_key}";
    path = path.replace("{hash_key}", pathSegment(hashKey));
    return this.transport.request<RetrieveResponse>("GET", path, undefined, null, "RetrieveResponse", schemas, options);
  }
}
