// Generated by tools.sdkgen; DO NOT EDIT.
import type { JsonValue } from "./runtime.js";

export interface RetrievalError {
  "detail": string;
  [key: string]: unknown; // Preserve future wire fields without renaming.
}

export interface RetrieveRequest {
  "hash": string;
  [key: string]: unknown; // Preserve future wire fields without renaming.
}

export interface RetrieveResponse {
  "compressed_item_count": number;
  "hash": string;
  "original_content": string;
  "original_item_count": number;
  "original_tokens": number;
  "retrieval_count": number;
  "tool_name": (string | null);
  [key: string]: unknown; // Preserve future wire fields without renaming.
}
