"""Deterministic .NET emitter for the JSON HTTP pilot profile."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..compiler import ContractError
from ..emit import operations, pascal, without_null

HERE = Path(__file__).resolve().parents[1]


def cs_ident(value: str) -> str:
    identifier = pascal(value)
    return (
        f"@{identifier}"
        if identifier in {"Class", "Namespace", "Event", "Params", "String"}
        else identifier
    )


def cs_type(schema: dict[str, Any]) -> str:
    if "enum" in schema:
        raise ContractError(".NET emitter does not support enum schemas")
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[1]
    if "anyOf" in schema:
        base = cs_type(without_null(schema))
        return base if base.endswith("?") else f"{base}?"
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind == "integer":
        return "long"
    if kind == "number":
        return "double"
    if kind == "boolean":
        return "bool"
    if kind == "array":
        return f"List<{cs_type(schema['items'])}>"
    if kind == "object":
        raise ContractError(".NET emitter does not support typed map or JsonValue schemas")
    raise ContractError(f"Unsupported .NET schema: {schema}")


def validation_lines(schema: dict[str, Any], expression: str, label: str, indent: str) -> list[str]:
    if "anyOf" in schema:
        base = without_null(schema)
        nested = validation_lines(base, expression, label, indent + "    ")
        if not nested:
            return []
        return [f"{indent}if ({expression} is not null)", f"{indent}{{", *nested, f"{indent}}}"]
    if "$ref" in schema:
        return [
            f'{indent}if ({expression} is null) throw new ProtocolException("Invalid field {label}");',
            f"{indent}{expression}.ValidateModel();",
        ]
    kind = schema.get("type")
    if kind == "string":
        return [
            f'{indent}if ({expression} is null) throw new ProtocolException("Invalid field {label}");'
        ]
    if kind == "array":
        item = schema["items"]
        nested = validation_lines(item, "item", f"{label}[]", indent + "        ")
        return [
            f'{indent}if ({expression} is null) throw new ProtocolException("Invalid field {label}");',
            f"{indent}foreach (var item in {expression})",
            f"{indent}{{",
            *nested,
            f"{indent}}}",
        ]
    return []


def emit_models(models: dict[str, Any]) -> bytes:
    lines = [
        "// Generated by tools.sdkgen; DO NOT EDIT.",
        "#nullable enable",
        "using System.Text.Json;",
        "using System.Text.Json.Serialization;",
        "",
        "namespace Headroom.GeneratedPilot;",
        "",
        "public interface IWireModel",
        "{",
        "    void ValidateModel();",
        "}",
        "",
        "[JsonConverter(typeof(OptionalJsonConverterFactory))]",
        "public readonly record struct Optional<T>(bool IsSet, T? Value)",
        "{",
        "    public static Optional<T> FromValue(T? value) => new(true, value);",
        "}",
        "",
        "public sealed class OptionalJsonConverterFactory : JsonConverterFactory",
        "{",
        "    public override bool CanConvert(Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Optional<>);",
        "    public override JsonConverter CreateConverter(Type type, JsonSerializerOptions options)",
        "    {",
        "        var valueType = type.GetGenericArguments()[0];",
        "        return (JsonConverter)Activator.CreateInstance(typeof(OptionalJsonConverter<>).MakeGenericType(valueType))!;",
        "    }",
        "    private sealed class OptionalJsonConverter<T> : JsonConverter<Optional<T>>",
        "    {",
        "        public override Optional<T> Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) =>",
        "            Optional<T>.FromValue(JsonSerializer.Deserialize<T>(ref reader, options));",
        "        public override void Write(Utf8JsonWriter writer, Optional<T> value, JsonSerializerOptions options) =>",
        "            JsonSerializer.Serialize(writer, value.Value, options);",
        "    }",
        "}",
        "",
    ]
    for model, schema in models.items():
        required = set(schema.get("required", []))
        lines += [f"public sealed class {model} : IWireModel, IJsonOnSerializing", "{"]
        for field, field_schema in schema["properties"].items():
            field_type = cs_type(field_schema)
            prefix = "required " if field in required else ""
            if field not in required:
                field_type = f"Optional<{field_type}>"
                lines.append("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]")
            lines += [
                f"    [JsonPropertyName({json.dumps(field)})]",
                f"    public {prefix}{field_type} {cs_ident(field)} {{ get; init; }}",
                "",
            ]
        lines += [
            "    [JsonExtensionData]",
            "    public Dictionary<string, JsonElement> AdditionalProperties { get; init; } = new();",
            "",
            "    public void OnSerializing()",
            "    {",
            "        foreach (var key in new string[] { "
            + ", ".join(json.dumps(field) for field in schema["properties"])
            + " })",
            "            if (AdditionalProperties.ContainsKey(key))",
            '                throw new JsonException($"Additional property shadows declared field {key}");',
            "    }",
            "",
            "    public void ValidateModel()",
            "    {",
        ]
        for field, field_schema in schema["properties"].items():
            field_name = cs_ident(field)
            if field in required:
                lines.extend(validation_lines(field_schema, field_name, field, "        "))
            else:
                nested = validation_lines(
                    field_schema, f"{field_name}.Value", field, "            "
                )
                if nested:
                    lines += [f"        if ({field_name}.IsSet)", "        {", *nested, "        }"]
        lines += [
            "    }",
            "}",
            "",
        ]
    return ("\n".join(lines).rstrip() + "\n").encode()


def emit_client(document: dict[str, Any]) -> bytes:
    lines = [
        "// Generated by tools.sdkgen; DO NOT EDIT.",
        "#nullable enable",
        "",
        "namespace Headroom.GeneratedPilot;",
        "",
        "public sealed class Client : IDisposable",
        "{",
        "    private readonly Transport transport;",
        '    public Client(string baseUrl = "http://localhost:8787", ClientOptions? options = null) =>',
        "        transport = new Transport(baseUrl, options ?? ClientOptions.Default);",
    ]
    for operation in operations(document):
        params = [f"string {param}" for param in operation["params"]]
        if operation["request"]:
            params.append(f"{operation['request']} body")
        params.append("CancellationToken cancellationToken = default")
        lines += [
            "",
            f"    public async Task<{operation['response']}> {pascal(operation['id'])}Async({', '.join(params)})",
            "    {",
            f"        var path = {json.dumps(operation['path'])};",
        ]
        for param in operation["params"]:
            lines.append(
                f"        path = path.Replace({json.dumps('{' + param + '}')}, Transport.PathSegment({param}), StringComparison.Ordinal);"
            )
        method = operation["method"].capitalize()
        if operation["request"]:
            lines.append(
                f"        return await transport.SendAsync<{operation['request']}, {operation['response']}>(HttpMethod.{method}, path, body, true, cancellationToken).ConfigureAwait(false);"
            )
        else:
            lines.append(
                f"        return await transport.SendAsync<object, {operation['response']}>(HttpMethod.{method}, path, null, false, cancellationToken).ConfigureAwait(false);"
            )
        lines += [
            "    }",
        ]
    lines += ["", "    public void Dispose() => transport.Dispose();", "}"]
    return ("\n".join(lines).rstrip() + "\n").encode()


def emit(document: dict[str, Any]) -> dict[str, bytes]:
    project = """<!-- Generated by tools.sdkgen; DO NOT EDIT. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
"""
    return {
        "dotnet/Headroom.GeneratedPilot.csproj": project.encode(),
        "dotnet/Models.cs": emit_models(document["components"]["schemas"]),
        "dotnet/Client.cs": emit_client(document),
        "dotnet/Runtime.cs": (HERE / "runtime/dotnet.cs").read_bytes(),
    }
