"""Deterministic Rust emitter for the JSON HTTP pilot profile."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..compiler import ContractError
from ..emit import operations, without_null

HERE = Path(__file__).resolve().parents[1]
RUST_KEYWORDS = {
    "as",
    "break",
    "const",
    "continue",
    "crate",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "Self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
    "async",
    "await",
    "dyn",
}


def rust_ident(value: str) -> str:
    return f"r#{value}" if value in RUST_KEYWORDS else value


def rust_type(schema: dict[str, Any]) -> str:
    if "enum" in schema:
        raise ContractError("Rust emitter does not support enum schemas")
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[1]
    if "anyOf" in schema:
        return f"Option<{rust_type(without_null(schema))}>"
    kind = schema.get("type")
    if kind == "string":
        return "String"
    if kind == "integer":
        return "i64"
    if kind == "number":
        return "f64"
    if kind == "boolean":
        return "bool"
    if kind == "array":
        return f"Vec<{rust_type(schema['items'])}>"
    if kind == "object":
        raise ContractError("Rust emitter does not support typed map or JsonValue schemas")
    raise ContractError(f"Unsupported Rust schema: {schema}")


def decode_expression(field: str, schema: dict[str, Any], required: bool) -> str:
    name = json.dumps(field)
    base = without_null(schema) if "anyOf" in schema else schema
    target = rust_type(base)
    if required and "anyOf" in schema:
        return (
            f"match take_required(&mut object, {name}).map_err(D::Error::custom)? {{ "
            f"Value::Null => None, value => Some(decode::<{target}>(value, {name}).map_err(D::Error::custom)?), }}"
        )
    if required:
        return f"decode::<{target}>(take_required(&mut object, {name}).map_err(D::Error::custom)?, {name}).map_err(D::Error::custom)?"
    if "anyOf" in schema:
        return (
            f"match object.remove({name}) {{ None => None, Some(Value::Null) => Some(None), "
            f"Some(value) => Some(Some(decode::<{target}>(value, {name}).map_err(D::Error::custom)?)), }}"
        )
    return (
        f"match object.remove({name}) {{ None => None, "
        f"Some(value) => Some(decode::<{target}>(value, {name}).map_err(D::Error::custom)?), }}"
    )


def emit_models(models: dict[str, Any]) -> bytes:
    lines = [
        "// Generated by tools.sdkgen; DO NOT EDIT.",
        "use serde::{de::{DeserializeOwned, Error as _}, Deserialize, Deserializer, Serialize};",
        "use serde_json::{Map, Value};",
        "",
        "fn take_required(object: &mut Map<String, Value>, name: &str) -> Result<Value, String> {",
        '    object.remove(name).ok_or_else(|| format!("missing required field {name}"))',
        "}",
        "",
        "fn decode<T: DeserializeOwned>(value: Value, name: &str) -> Result<T, String> {",
        '    serde_json::from_value(value).map_err(|_error| format!("invalid field {name}"))',
        "}",
        "",
    ]
    for model, schema in models.items():
        required = set(schema.get("required", []))
        lines += ["#[derive(Debug, Clone, PartialEq, Serialize)]", f"pub struct {model} {{"]
        for field, field_schema in schema["properties"].items():
            field_type = rust_type(field_schema)
            if field not in required:
                field_type = f"Option<{field_type}>"
            serde_options = f"rename = {json.dumps(field)}"
            if field not in required:
                serde_options += ', skip_serializing_if = "Option::is_none"'
            lines += [
                f"    #[serde({serde_options})]",
                f"    pub {rust_ident(field)}: {field_type},",
            ]
        lines += [
            "    #[serde(flatten)]",
            "    pub additional_properties: Map<String, Value>,",
            "}",
            "",
            f"impl<'de> Deserialize<'de> for {model} {{",
            "    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {",
            "        let mut object = Map::<String, Value>::deserialize(deserializer)?;",
        ]
        for field, field_schema in schema["properties"].items():
            expression = decode_expression(field, field_schema, field in required)
            lines.append(f"        let {rust_ident(field)} = {expression};")
        lines += ["        Ok(Self {"]
        for field in schema["properties"]:
            lines.append(f"            {rust_ident(field)},")
        lines += ["            additional_properties: object,", "        })", "    }", "}", ""]
    if "RetrieveResponse" in models:
        lines += [
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "",
            "    #[test]",
            "    fn required_nullable_accepts_null_and_rejects_omission() {",
            '        let valid = r#"{"hash":"h","original_content":"x","original_tokens":1,"original_item_count":1,"compressed_item_count":1,"tool_name":null,"retrieval_count":1}"#;',
            '        let parsed: RetrieveResponse = serde_json::from_str(valid).expect("explicit null is valid");',
            "        assert_eq!(parsed.tool_name, None);",
            '        let missing = r#"{"hash":"h","original_content":"x","original_tokens":1,"original_item_count":1,"compressed_item_count":1,"retrieval_count":1}"#;',
            "        assert!(serde_json::from_str::<RetrieveResponse>(missing).is_err());",
            "    }",
            "}",
        ]
    return ("\n".join(lines).rstrip() + "\n").encode()


def emit_client(document: dict[str, Any]) -> bytes:
    operation_list = operations(document)
    runtime_imports = "Error, Options, Transport"
    if any(operation["params"] for operation in operation_list):
        runtime_imports = "path_segment, " + runtime_imports
    lines = [
        "// Generated by tools.sdkgen; DO NOT EDIT.",
        "use reqwest::Method;",
        f"use crate::{{models::*, runtime::{{{runtime_imports}}}}};",
        "",
        "pub struct Client {",
        "    transport: Transport,",
        "}",
        "",
        "impl Client {",
        "    pub fn new(base_url: &str, options: Options) -> Result<Self, Error> {",
        "        Ok(Self { transport: Transport::new(base_url, options)? })",
        "    }",
    ]
    for operation in operation_list:
        params = [f"{rust_ident(param)}: &str" for param in operation["params"]]
        if operation["request"]:
            params.append(f"body: &{operation['request']}")
        lines += [
            "",
            f"    pub async fn {rust_ident(operation['id'])}(&self, {', '.join(params)}) -> Result<{operation['response']}, Error> {{",
            f"        let {'mut ' if operation['params'] else ''}path = {json.dumps(operation['path'])}.to_owned();",
        ]
        for param in operation["params"]:
            lines.append(
                f"        path = path.replace({json.dumps('{' + param + '}')}, &path_segment({rust_ident(param)})?);"
            )
        method = operation["method"].upper()
        if operation["request"]:
            lines.append(
                f"        self.transport.request(Method::{method}, &path, Some(body)).await"
            )
        else:
            lines.append(
                f"        self.transport.request::<(), _>(Method::{method}, &path, None).await"
            )
        lines += [
            "    }",
        ]
    lines += ["}"]
    return ("\n".join(lines).rstrip() + "\n").encode()


def emit(document: dict[str, Any]) -> dict[str, bytes]:
    models = document["components"]["schemas"]
    cargo = """# Generated by tools.sdkgen; DO NOT EDIT.
[package]
name = "headroom-generated-pilot"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
percent-encoding = "=2.3.2"
reqwest = { version = "=0.12.28", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"

[dev-dependencies]
tokio = { version = "=1.47.1", features = ["macros", "rt-multi-thread", "time"] }
"""
    lib = """// Generated by tools.sdkgen; DO NOT EDIT.
pub mod client;
pub mod models;
pub mod runtime;

pub use client::Client;
pub use models::*;
pub use runtime::{APIError, Error, Options};
"""
    return {
        "rust/Cargo.toml": cargo.encode(),
        "rust/Cargo.lock": (HERE / "runtime/rust.Cargo.lock").read_bytes(),
        "rust/src/lib.rs": lib.encode(),
        "rust/src/models.rs": emit_models(models),
        "rust/src/client.rs": emit_client(document),
        "rust/src/runtime.rs": (HERE / "runtime/rust.rs").read_bytes(),
    }
