// Code generated by tools.sdkgen. DO NOT EDIT.
package headroomwire

import ("context"; "strings")

type Client struct { transport *Transport }
func NewClient(baseURL string, options *Options) (*Client, error) {
    transport, err := newTransport(baseURL, options); if err != nil { return nil, err }
    return &Client{transport: transport}, nil
}
func (c *Client) Retrieve(ctx context.Context, body RetrieveRequest) (*RetrieveResponse, error) {
    path := "/v1/retrieve"
    var out RetrieveResponse
    if err := c.transport.request(ctx, "POST", path, body, &out, "RetrieveRequest"); err != nil { return nil, err }
    return &out, nil
}
func (c *Client) RetrieveGet(ctx context.Context, hashKey string) (*RetrieveResponse, error) {
    path := "/v1/retrieve/{hash_key}"
    encodedHashKey, err := pathSegment(hashKey); if err != nil { return nil, err }
    path = strings.ReplaceAll(path, "{hash_key}", encodedHashKey)
    var out RetrieveResponse
    if err := c.transport.request(ctx, "GET", path, nil, &out, ""); err != nil { return nil, err }
    return &out, nil
}
