// Code generated by tools.sdkgen. DO NOT EDIT.
package headroomwire

import ("encoding/json"; "fmt")

type RetrievalError struct {
    Detail string `json:"detail"`
    AdditionalProperties map[string]json.RawMessage `json:"-"`
}
func (x RetrievalError) MarshalJSON() ([]byte, error) {
    fields := make(map[string]json.RawMessage, len(x.AdditionalProperties))
    for key, value := range x.AdditionalProperties { fields[key] = value }
    if _, exists := fields["detail"]; exists { return nil, fmt.Errorf("additional property collides with declared field detail") }
    if true {
        raw, err := json.Marshal(x.Detail); if err != nil { return nil, err }
        fields["detail"] = raw
    }
    raw, err := json.Marshal(fields); if err != nil { return nil, err }
    if err := validateModel(raw, "RetrievalError"); err != nil { return nil, err }
    return raw, nil
}
func (x *RetrievalError) UnmarshalJSON(raw []byte) error {
    if err := validateModel(raw, "RetrievalError"); err != nil { return err }
    type plain RetrievalError
    var value plain
    if err := json.Unmarshal(raw, &value); err != nil { return err }
    var extra map[string]json.RawMessage
    if err := json.Unmarshal(raw, &extra); err != nil { return err }
    delete(extra, "detail")
    *x = RetrievalError(value); x.AdditionalProperties = extra
    return nil
}

type RetrieveRequest struct {
    Hash string `json:"hash"`
    AdditionalProperties map[string]json.RawMessage `json:"-"`
}
func (x RetrieveRequest) MarshalJSON() ([]byte, error) {
    fields := make(map[string]json.RawMessage, len(x.AdditionalProperties))
    for key, value := range x.AdditionalProperties { fields[key] = value }
    if _, exists := fields["hash"]; exists { return nil, fmt.Errorf("additional property collides with declared field hash") }
    if true {
        raw, err := json.Marshal(x.Hash); if err != nil { return nil, err }
        fields["hash"] = raw
    }
    raw, err := json.Marshal(fields); if err != nil { return nil, err }
    if err := validateModel(raw, "RetrieveRequest"); err != nil { return nil, err }
    return raw, nil
}
func (x *RetrieveRequest) UnmarshalJSON(raw []byte) error {
    if err := validateModel(raw, "RetrieveRequest"); err != nil { return err }
    type plain RetrieveRequest
    var value plain
    if err := json.Unmarshal(raw, &value); err != nil { return err }
    var extra map[string]json.RawMessage
    if err := json.Unmarshal(raw, &extra); err != nil { return err }
    delete(extra, "hash")
    *x = RetrieveRequest(value); x.AdditionalProperties = extra
    return nil
}

type RetrieveResponse struct {
    CompressedItemCount int64 `json:"compressed_item_count"`
    Hash string `json:"hash"`
    OriginalContent string `json:"original_content"`
    OriginalItemCount int64 `json:"original_item_count"`
    OriginalTokens int64 `json:"original_tokens"`
    RetrievalCount int64 `json:"retrieval_count"`
    ToolName *string `json:"tool_name"`
    AdditionalProperties map[string]json.RawMessage `json:"-"`
}
func (x RetrieveResponse) MarshalJSON() ([]byte, error) {
    fields := make(map[string]json.RawMessage, len(x.AdditionalProperties))
    for key, value := range x.AdditionalProperties { fields[key] = value }
    if _, exists := fields["compressed_item_count"]; exists { return nil, fmt.Errorf("additional property collides with declared field compressed_item_count") }
    if true {
        raw, err := json.Marshal(x.CompressedItemCount); if err != nil { return nil, err }
        fields["compressed_item_count"] = raw
    }
    if _, exists := fields["hash"]; exists { return nil, fmt.Errorf("additional property collides with declared field hash") }
    if true {
        raw, err := json.Marshal(x.Hash); if err != nil { return nil, err }
        fields["hash"] = raw
    }
    if _, exists := fields["original_content"]; exists { return nil, fmt.Errorf("additional property collides with declared field original_content") }
    if true {
        raw, err := json.Marshal(x.OriginalContent); if err != nil { return nil, err }
        fields["original_content"] = raw
    }
    if _, exists := fields["original_item_count"]; exists { return nil, fmt.Errorf("additional property collides with declared field original_item_count") }
    if true {
        raw, err := json.Marshal(x.OriginalItemCount); if err != nil { return nil, err }
        fields["original_item_count"] = raw
    }
    if _, exists := fields["original_tokens"]; exists { return nil, fmt.Errorf("additional property collides with declared field original_tokens") }
    if true {
        raw, err := json.Marshal(x.OriginalTokens); if err != nil { return nil, err }
        fields["original_tokens"] = raw
    }
    if _, exists := fields["retrieval_count"]; exists { return nil, fmt.Errorf("additional property collides with declared field retrieval_count") }
    if true {
        raw, err := json.Marshal(x.RetrievalCount); if err != nil { return nil, err }
        fields["retrieval_count"] = raw
    }
    if _, exists := fields["tool_name"]; exists { return nil, fmt.Errorf("additional property collides with declared field tool_name") }
    if true {
        raw, err := json.Marshal(x.ToolName); if err != nil { return nil, err }
        fields["tool_name"] = raw
    }
    raw, err := json.Marshal(fields); if err != nil { return nil, err }
    if err := validateModel(raw, "RetrieveResponse"); err != nil { return nil, err }
    return raw, nil
}
func (x *RetrieveResponse) UnmarshalJSON(raw []byte) error {
    if err := validateModel(raw, "RetrieveResponse"); err != nil { return err }
    type plain RetrieveResponse
    var value plain
    if err := json.Unmarshal(raw, &value); err != nil { return err }
    var extra map[string]json.RawMessage
    if err := json.Unmarshal(raw, &extra); err != nil { return err }
    delete(extra, "compressed_item_count")
    delete(extra, "hash")
    delete(extra, "original_content")
    delete(extra, "original_item_count")
    delete(extra, "original_tokens")
    delete(extra, "retrieval_count")
    delete(extra, "tool_name")
    *x = RetrieveResponse(value); x.AdditionalProperties = extra
    return nil
}
