//! End-to-end coverage for published TOIN advice at native dispatch.

use headroom_core::transforms::live_zone::{
    compress_anthropic_live_zone_with_recommendations,
    compress_openai_chat_live_zone_with_recommendations,
    compress_openai_responses_live_zone_with_recommendations, AuthMode, BlockAction,
    LiveZoneOutcome, DEFAULT_MODEL,
};
use headroom_core::transforms::recommendations::RecommendationStore;
use serde_json::json;

fn body_with_json_tool_result() -> Vec<u8> {
    let items: Vec<_> = (0..80)
        .map(|index| json!({"id": index, "name": format!("item-{index}"), "status": "active"}))
        .collect();
    let content = serde_json::to_string(&items).expect("content serializes");
    serde_json::to_vec(&json!({
        "model": DEFAULT_MODEL,
        "messages": [{
            "role": "user",
            "content": [{"type": "tool_result", "tool_use_id": "tool-1", "content": content}]
        }]
    }))
    .expect("body serializes")
}

fn json_tool_result() -> String {
    let items: Vec<_> = (0..80)
        .map(|index| json!({"id": index, "name": format!("item-{index}"), "status": "active"}))
        .collect();
    serde_json::to_string(&items).expect("content serializes")
}

fn skip_store() -> RecommendationStore {
    RecommendationStore::from_toml_str(
        r#"
[[recommendation]]
auth_mode = "unknown"
model_family = "unknown"
structure_hash = "01b5d1d54e702e06ddd21168"
skip_compression_recommended = true
strategy_hint = "skip_compression"
confidence = 0.92
observations = 240
"#,
    )
    .expect("recommendations parse")
}

fn assert_recommendation_skip(outcome: LiveZoneOutcome) {
    let LiveZoneOutcome::NoChange { manifest } = outcome else {
        panic!("skip recommendation must preserve the original body");
    };
    assert!(manifest.block_outcomes.iter().any(|block| matches!(
        &block.action,
        BlockAction::SkippedByRecommendation {
            structure_hash,
            confidence,
            observations: 240,
        } if structure_hash == "01b5d1d54e702e06ddd21168" && (*confidence - 0.92).abs() < 1e-9
    )));
    assert_eq!(manifest.tokens_saved(), 0);
    assert!(manifest.transforms_applied().is_empty());
}

#[test]
fn published_skip_changes_dispatch_to_explicit_no_change() {
    let body = body_with_json_tool_result();
    let empty = RecommendationStore::empty();
    let baseline = compress_anthropic_live_zone_with_recommendations(
        &body,
        0,
        AuthMode::Payg,
        DEFAULT_MODEL,
        None,
        &empty,
    )
    .expect("baseline dispatch");
    assert!(matches!(baseline, LiveZoneOutcome::Modified { .. }));

    // Hash generated by Python ToolSignature.from_items for
    // [(id: numeric, name: string, status: string)]. The unknown slice
    // proves legacy observations remain useful after auth/model wiring.
    let store = skip_store();

    let advised = compress_anthropic_live_zone_with_recommendations(
        &body,
        0,
        AuthMode::Payg,
        DEFAULT_MODEL,
        None,
        &store,
    )
    .expect("recommended dispatch");

    assert_recommendation_skip(advised);
}

#[test]
fn published_skip_is_applied_to_openai_chat_dispatch() {
    let body = serde_json::to_vec(&json!({
        "model": "gpt-4o",
        "messages": [{"role": "tool", "tool_call_id": "call-1", "content": json_tool_result()}]
    }))
    .expect("body serializes");
    let empty = RecommendationStore::empty();
    let baseline = compress_openai_chat_live_zone_with_recommendations(
        &body,
        AuthMode::Payg,
        "gpt-4o",
        &empty,
    )
    .expect("baseline dispatch");
    assert!(matches!(baseline, LiveZoneOutcome::Modified { .. }));

    let advised = compress_openai_chat_live_zone_with_recommendations(
        &body,
        AuthMode::Payg,
        "gpt-4o",
        &skip_store(),
    )
    .expect("recommended dispatch");
    assert_recommendation_skip(advised);
}

#[test]
fn published_skip_is_applied_to_openai_responses_dispatch() {
    let body = serde_json::to_vec(&json!({
        "model": "gpt-4o",
        "input": [{"type": "function_call_output", "call_id": "call-1", "output": json_tool_result()}]
    }))
    .expect("body serializes");
    let empty = RecommendationStore::empty();
    let baseline = compress_openai_responses_live_zone_with_recommendations(
        &body,
        AuthMode::Payg,
        "gpt-4o",
        &empty,
    )
    .expect("baseline dispatch");
    assert!(matches!(baseline, LiveZoneOutcome::Modified { .. }));

    let advised = compress_openai_responses_live_zone_with_recommendations(
        &body,
        AuthMode::Payg,
        "gpt-4o",
        &skip_store(),
    )
    .expect("recommended dispatch");
    assert_recommendation_skip(advised);
}

#[test]
fn unrelated_recommendation_leaves_dispatch_unchanged() {
    let body = body_with_json_tool_result();
    let store = RecommendationStore::from_toml_str(
        r#"
[[recommendation]]
auth_mode = "payg"
model_family = "claude-3-5"
structure_hash = "ffffffffffffffffffffffff"
skip_compression_recommended = true
strategy_hint = "skip_compression"
confidence = 0.99
observations = 999
"#,
    )
    .expect("recommendations parse");

    let outcome = compress_anthropic_live_zone_with_recommendations(
        &body,
        0,
        AuthMode::Payg,
        DEFAULT_MODEL,
        None,
        &store,
    )
    .expect("dispatch");
    assert!(matches!(outcome, LiveZoneOutcome::Modified { .. }));
}
