# Generated by tools.sdkgen; DO NOT EDIT.
from __future__ import annotations

from typing import Any, cast
from .runtime import Transport, path_segment
from .models import RetrievalError, RetrieveRequest, RetrieveResponse


class Client:
    def __init__(self, base_url: str = "http://localhost:8787", *, transport: Transport | None = None, **options: Any) -> None:
        self._transport = transport or Transport(base_url, **options)

    def retrieve(self, body: RetrieveRequest) -> RetrieveResponse:
        path = '/v1/retrieve'
        return cast(RetrieveResponse, self._transport.request('POST', path, body, 'RetrieveRequest', 'RetrieveResponse'))

    def retrieve_get(self, hash_key: str) -> RetrieveResponse:
        path = '/v1/retrieve/{hash_key}'
        path = path.replace('{hash_key}', path_segment(hash_key))
        return cast(RetrieveResponse, self._transport.request('GET', path, None, None, 'RetrieveResponse'))
