# Generated by tools.sdkgen; DO NOT EDIT.
from __future__ import annotations

from typing import Literal, NotRequired, TypeAlias, TypedDict

JsonValue: TypeAlias = "None | bool | int | float | str | list[JsonValue] | dict[str, JsonValue]"

RetrievalError = TypedDict('RetrievalError', {
    'detail': 'str',
})

RetrieveRequest = TypedDict('RetrieveRequest', {
    'hash': 'str',
})

RetrieveResponse = TypedDict('RetrieveResponse', {
    'compressed_item_count': 'int',
    'hash': 'str',
    'original_content': 'str',
    'original_item_count': 'int',
    'original_tokens': 'int',
    'retrieval_count': 'int',
    'tool_name': 'str | None',
})
