// Generated by tools.sdkgen; DO NOT EDIT.
use reqwest::Method;
use crate::{models::*, runtime::{path_segment, Error, Options, Transport}};

pub struct Client {
    transport: Transport,
}

impl Client {
    pub fn new(base_url: &str, options: Options) -> Result<Self, Error> {
        Ok(Self { transport: Transport::new(base_url, options)? })
    }

    pub async fn retrieve(&self, body: &RetrieveRequest) -> Result<RetrieveResponse, Error> {
        let path = "/v1/retrieve".to_owned();
        self.transport.request(Method::POST, &path, Some(body)).await
    }

    pub async fn retrieve_get(&self, hash_key: &str) -> Result<RetrieveResponse, Error> {
        let mut path = "/v1/retrieve/{hash_key}".to_owned();
        path = path.replace("{hash_key}", &path_segment(hash_key)?);
        self.transport.request::<(), _>(Method::GET, &path, None).await
    }
}
