// Generated by tools.sdkgen; DO NOT EDIT.
use serde::{de::{DeserializeOwned, Error as _}, Deserialize, Deserializer, Serialize};
use serde_json::{Map, Value};

fn take_required(object: &mut Map<String, Value>, name: &str) -> Result<Value, String> {
    object.remove(name).ok_or_else(|| format!("missing required field {name}"))
}

fn decode<T: DeserializeOwned>(value: Value, name: &str) -> Result<T, String> {
    serde_json::from_value(value).map_err(|_error| format!("invalid field {name}"))
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct RetrievalError {
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(flatten, serialize_with = "serialize_retrievalerror_extensions")]
    pub additional_properties: Map<String, Value>,
}

fn serialize_retrievalerror_extensions<S: serde::Serializer>(value: &Map<String, Value>, serializer: S) -> Result<S::Ok, S::Error> {
    let known: &[&str] = &["detail"];
    for name in known {
        if value.contains_key(*name) {
            return Err(serde::ser::Error::custom(format!("additional property shadows declared field {}", name)));
        }
    }
    value.serialize(serializer)
}

impl<'de> Deserialize<'de> for RetrievalError {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut object = Map::<String, Value>::deserialize(deserializer)?;
        let detail = decode::<String>(take_required(&mut object, "detail").map_err(D::Error::custom)?, "detail").map_err(D::Error::custom)?;
        Ok(Self {
            detail,
            additional_properties: object,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct RetrieveRequest {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(flatten, serialize_with = "serialize_retrieverequest_extensions")]
    pub additional_properties: Map<String, Value>,
}

fn serialize_retrieverequest_extensions<S: serde::Serializer>(value: &Map<String, Value>, serializer: S) -> Result<S::Ok, S::Error> {
    let known: &[&str] = &["hash"];
    for name in known {
        if value.contains_key(*name) {
            return Err(serde::ser::Error::custom(format!("additional property shadows declared field {}", name)));
        }
    }
    value.serialize(serializer)
}

impl<'de> Deserialize<'de> for RetrieveRequest {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut object = Map::<String, Value>::deserialize(deserializer)?;
        let hash = decode::<String>(take_required(&mut object, "hash").map_err(D::Error::custom)?, "hash").map_err(D::Error::custom)?;
        Ok(Self {
            hash,
            additional_properties: object,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct RetrieveResponse {
    #[serde(rename = "compressed_item_count")]
    pub compressed_item_count: i64,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "original_content")]
    pub original_content: String,
    #[serde(rename = "original_item_count")]
    pub original_item_count: i64,
    #[serde(rename = "original_tokens")]
    pub original_tokens: i64,
    #[serde(rename = "retrieval_count")]
    pub retrieval_count: i64,
    #[serde(rename = "tool_name")]
    pub tool_name: Option<String>,
    #[serde(flatten, serialize_with = "serialize_retrieveresponse_extensions")]
    pub additional_properties: Map<String, Value>,
}

fn serialize_retrieveresponse_extensions<S: serde::Serializer>(value: &Map<String, Value>, serializer: S) -> Result<S::Ok, S::Error> {
    let known: &[&str] = &["compressed_item_count", "hash", "original_content", "original_item_count", "original_tokens", "retrieval_count", "tool_name"];
    for name in known {
        if value.contains_key(*name) {
            return Err(serde::ser::Error::custom(format!("additional property shadows declared field {}", name)));
        }
    }
    value.serialize(serializer)
}

impl<'de> Deserialize<'de> for RetrieveResponse {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut object = Map::<String, Value>::deserialize(deserializer)?;
        let compressed_item_count = decode::<i64>(take_required(&mut object, "compressed_item_count").map_err(D::Error::custom)?, "compressed_item_count").map_err(D::Error::custom)?;
        let hash = decode::<String>(take_required(&mut object, "hash").map_err(D::Error::custom)?, "hash").map_err(D::Error::custom)?;
        let original_content = decode::<String>(take_required(&mut object, "original_content").map_err(D::Error::custom)?, "original_content").map_err(D::Error::custom)?;
        let original_item_count = decode::<i64>(take_required(&mut object, "original_item_count").map_err(D::Error::custom)?, "original_item_count").map_err(D::Error::custom)?;
        let original_tokens = decode::<i64>(take_required(&mut object, "original_tokens").map_err(D::Error::custom)?, "original_tokens").map_err(D::Error::custom)?;
        let retrieval_count = decode::<i64>(take_required(&mut object, "retrieval_count").map_err(D::Error::custom)?, "retrieval_count").map_err(D::Error::custom)?;
        let tool_name = match take_required(&mut object, "tool_name").map_err(D::Error::custom)? { Value::Null => None, value => Some(decode::<String>(value, "tool_name").map_err(D::Error::custom)?), };
        Ok(Self {
            compressed_item_count,
            hash,
            original_content,
            original_item_count,
            original_tokens,
            retrieval_count,
            tool_name,
            additional_properties: object,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn required_nullable_accepts_null_and_rejects_omission() {
        let valid = r#"{"hash":"h","original_content":"x","original_tokens":1,"original_item_count":1,"compressed_item_count":1,"tool_name":null,"retrieval_count":1}"#;
        let parsed: RetrieveResponse = serde_json::from_str(valid).expect("explicit null is valid");
        assert_eq!(parsed.tool_name, None);
        let missing = r#"{"hash":"h","original_content":"x","original_tokens":1,"original_item_count":1,"compressed_item_count":1,"retrieval_count":1}"#;
        assert!(serde_json::from_str::<RetrieveResponse>(missing).is_err());
    }
}
