// Generated by tools.sdkgen; DO NOT EDIT.
use percent_encoding::{utf8_percent_encode, NON_ALPHANUMERIC};
use reqwest::{header::HeaderMap, redirect::Policy, Method, Url};
use serde::{de::DeserializeOwned, Serialize};
use std::{fmt, time::Duration};

#[derive(Debug, Clone)]
pub struct Options {
    pub timeout: Duration,
    pub max_response_bytes: usize,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            timeout: Duration::from_secs(30),
            max_response_bytes: 8 * 1024 * 1024,
        }
    }
}

#[derive(Debug)]
pub struct APIError {
    pub status: u16,
    pub headers: HeaderMap,
    pub body: Vec<u8>,
}

impl fmt::Display for APIError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "Headroom API returned HTTP {}", self.status)
    }
}

impl std::error::Error for APIError {}

#[derive(Debug)]
pub enum Error {
    Transport(reqwest::Error),
    Protocol(String),
    API(Box<APIError>),
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Transport(error) => write!(formatter, "transport error: {error}"),
            Self::Protocol(message) => write!(formatter, "protocol error: {message}"),
            Self::API(error) => error.fmt(formatter),
        }
    }
}

impl std::error::Error for Error {}

pub struct Transport {
    client: reqwest::Client,
    base_url: String,
    max_response_bytes: usize,
}

impl Transport {
    pub fn new(base_url: &str, options: Options) -> Result<Self, Error> {
        let parsed = Url::parse(base_url).map_err(|error| Error::Protocol(error.to_string()))?;
        if !matches!(parsed.scheme(), "http" | "https")
            || parsed.username() != ""
            || parsed.password().is_some()
            || parsed.query().is_some()
            || parsed.fragment().is_some()
        {
            return Err(Error::Protocol("base URL must be an http(s) origin with an optional path".into()));
        }
        let client = reqwest::Client::builder()
            .redirect(Policy::none())
            .retry(reqwest::retry::never())
            .timeout(options.timeout)
            .build()
            .map_err(Error::Transport)?;
        Ok(Self {
            client,
            base_url: base_url.trim_end_matches('/').to_owned(),
            max_response_bytes: options.max_response_bytes,
        })
    }

    pub async fn request<B, R>(
        &self,
        method: Method,
        path: &str,
        body: Option<&B>,
    ) -> Result<R, Error>
    where
        B: Serialize + ?Sized,
        R: DeserializeOwned,
    {
        let url = format!("{}{path}", self.base_url);
        let mut request = self.client.request(method, url);
        if let Some(body) = body {
            request = request.json(body);
        }
        let mut response = request.send().await.map_err(Error::Transport)?;
        let status = response.status();
        let headers = response.headers().clone();
        let mut bytes = Vec::new();
        while let Some(chunk) = response.chunk().await.map_err(Error::Transport)? {
            if bytes.len().saturating_add(chunk.len()) > self.max_response_bytes {
                return Err(Error::Protocol("response exceeds max_response_bytes".into()));
            }
            bytes.extend_from_slice(&chunk);
        }
        if !status.is_success() {
            return Err(Error::API(Box::new(APIError {
                status: status.as_u16(),
                headers,
                body: bytes,
            })));
        }
        let media_type = headers
            .get(reqwest::header::CONTENT_TYPE)
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.split(';').next())
            .map(str::trim)
            .map(str::to_ascii_lowercase)
            .unwrap_or_default();
        if media_type != "application/json" && !media_type.ends_with("+json") {
            return Err(Error::Protocol("Expected a JSON Content-Type".into()));
        }
        serde_json::from_slice(&bytes).map_err(|_error| {
            Error::Protocol("Response does not match the declared wire model".into())
        })
    }
}

pub fn path_segment(value: &str) -> Result<String, Error> {
    if matches!(value, "." | "..") {
        return Err(Error::Protocol("dot path segments are not allowed".into()));
    }
    Ok(utf8_percent_encode(value, NON_ALPHANUMERIC).to_string())
}
