// Generated by tools.sdkgen; DO NOT EDIT.
#nullable enable
using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace Headroom.GeneratedPilot;

public sealed record ClientOptions(TimeSpan Timeout, int MaxResponseBytes)
{
    public static ClientOptions Default { get; } = new(TimeSpan.FromSeconds(30), 8 * 1024 * 1024);
}

public sealed class APIException : Exception
{
    public HttpStatusCode StatusCode { get; }
    public IReadOnlyDictionary<string, string[]> Headers { get; }
    public byte[] Body { get; }

    public APIException(HttpStatusCode statusCode, IReadOnlyDictionary<string, string[]> headers, byte[] body)
        : base($"Headroom API returned HTTP {(int)statusCode}")
    {
        StatusCode = statusCode;
        Headers = headers;
        Body = body;
    }
}

public sealed class ProtocolException : Exception
{
    public ProtocolException(string message, Exception? inner = null) : base(message, inner) { }
}

internal sealed class Transport : IDisposable
{
    private readonly HttpClient client;
    private readonly string baseUrl;
    private readonly TimeSpan timeout;
    private readonly int maxResponseBytes;

    public Transport(string baseUrl, ClientOptions options)
    {
        if (!Uri.TryCreate(baseUrl, UriKind.Absolute, out var uri)
            || (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps)
            || !string.IsNullOrEmpty(uri.UserInfo)
            || !string.IsNullOrEmpty(uri.Query)
            || !string.IsNullOrEmpty(uri.Fragment))
        {
            throw new ArgumentException("Base URL must be an http(s) origin with an optional path", nameof(baseUrl));
        }
        var handler = new SocketsHttpHandler { AllowAutoRedirect = false };
        client = new HttpClient(handler) { Timeout = Timeout.InfiniteTimeSpan };
        this.baseUrl = baseUrl.TrimEnd('/');
        timeout = options.Timeout;
        maxResponseBytes = options.MaxResponseBytes;
    }

    public async Task<TResponse> SendAsync<TRequest, TResponse>(
        HttpMethod method,
        string path,
        TRequest? body,
        bool hasBody,
        CancellationToken cancellationToken)
    {
        using var linked = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        linked.CancelAfter(timeout);
        using var request = new HttpRequestMessage(method, baseUrl + path);
        if (hasBody)
        {
            if (body is IWireModel requestModel) requestModel.ValidateModel();
            var json = JsonSerializer.Serialize(body);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
        }
        using var response = await client.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead,
            linked.Token).ConfigureAwait(false);
        var bytes = await ReadBoundedAsync(response.Content, linked.Token).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            var headers = response.Headers.Concat(response.Content.Headers)
                .ToDictionary(pair => pair.Key, pair => pair.Value.ToArray(), StringComparer.OrdinalIgnoreCase);
            throw new APIException(response.StatusCode, headers, bytes);
        }
        var mediaType = response.Content.Headers.ContentType?.MediaType;
        if (mediaType is null
            || (!mediaType.Equals("application/json", StringComparison.OrdinalIgnoreCase)
                && !mediaType.EndsWith("+json", StringComparison.OrdinalIgnoreCase)))
        {
            throw new ProtocolException("Expected a JSON Content-Type");
        }
        try
        {
            var result = JsonSerializer.Deserialize<TResponse>(bytes)
                ?? throw new ProtocolException("Response JSON decoded to null");
            if (result is IWireModel responseModel) responseModel.ValidateModel();
            return result;
        }
        catch (JsonException error)
        {
            throw new ProtocolException("Response does not match the declared wire model", error);
        }
    }

    private async Task<byte[]> ReadBoundedAsync(HttpContent content, CancellationToken cancellationToken)
    {
        await using var stream = await content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(false);
        using var output = new MemoryStream();
        var buffer = new byte[8192];
        while (true)
        {
            var count = await stream.ReadAsync(buffer, cancellationToken).ConfigureAwait(false);
            if (count == 0) break;
            if (output.Length + count > maxResponseBytes)
                throw new ProtocolException("Response exceeds maxResponseBytes");
            output.Write(buffer, 0, count);
        }
        return output.ToArray();
    }

    public static string PathSegment(string value)
    {
        if (value is "." or "..") throw new ArgumentException("Dot path segments are not allowed", nameof(value));
        return Uri.EscapeDataString(value);
    }

    public void Dispose() => client.Dispose();
}
